name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags, e.g., v1.0, v1.1.0

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    # Note: Make sure your compilation job in the workflow is actually named "build"
    needs: build  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Rename Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-linux
          path: ./artifacts
      - name: Rename Linux File
        run: mv ./artifacts/mari0_ae-linux ./artifacts/alesan99s_entities_${{ github.ref_name }}.AppImage

      - name: Download and Rename macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-macos
          path: ./artifacts
      - name: Rename macOS File
        run: mv ./artifacts/mari0_ae-macos ./artifacts/alesan99s_entities_${{ github.ref_name }}-macos.zip

      - name: Download and Rename Windows 64-bit Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-win64
          path: ./artifacts
      - name: Rename Windows File
        run: mv ./artifacts/mari0_ae-win64 ./artifacts/alesan99s_entities_${{ github.ref_name }}-win64.zip
